using ApiCreacionDocs.Models;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OriginaWebApp.Models.Formatos
{
    public class fmtfmtEstipulacion
    {
        public string strDocumento;

        public string FormatoHTML(InputData data)
        {


            strDocumento = @"																									";
            strDocumento += @"<html>                                                                                                                                                    ";
            strDocumento += @"<head>                                                                                                                                                    ";
            strDocumento += @"    <style>                                                                                                                                               ";
            strDocumento += @"        p.b {                                                                                                                                             ";
            strDocumento += @"            font-family: Arial;                                                                                                                           ";
            strDocumento += @"            font-size: 12px;                                                                                                                              ";
            strDocumento += @"        }                                                                                                                                                 ";
            strDocumento += @"                                                                                                                                                          ";
            strDocumento += @"        p.negrita {                                                                                                                                       ";
            strDocumento += @"            font-family: Arial;                                                                                                                           ";
            strDocumento += @"            font-weight: bold;                                                                                                                            ";
            strDocumento += @"        }                                                                                                                                                 ";
            strDocumento += @"                                                                                                                                                          ";
            strDocumento += @"        font.l {                                                                                                                                          ";
            strDocumento += @"            font-weight: bold;                                                                                                                            ";
            strDocumento += @"        }                                                                                                                                                 ";
            strDocumento += @"                                                                                                                                                          ";
            strDocumento += @"        font.z {                                                                                                                                          ";
            strDocumento += @"            text-align: right;                                                                                                                            ";
            strDocumento += @"        }                                                                                                                                                 ";
            strDocumento += @"                                                                                                                                                          ";
            strDocumento += @"        p.solid {                                                                                                                                         ";
            strDocumento += @"            border-style: solid;                                                                                                                          ";
            strDocumento += @"        }                                                                                                                                                 ";
            strDocumento += @"    </style>                                                                                                                                              ";
            strDocumento += @"    <meta name=""tipo_contenido"" content=""text/html;"" http-equiv=""content-type"" charset=""utf-8"">                                                   ";
            strDocumento += @"</head>                                                                                                                                                   ";
            strDocumento += @"                                                                                                                                                          ";
            strDocumento += @"<body style=""text-align: justify;"">                                                                                                                     ";
            strDocumento += @"    <p align=""center""><b>ESTIPULACIÓN A FAVOR DE FOMEPADE</b></p>                                                                                       ";
            strDocumento += @"    <img align=""left"" src=""C:\Users\DanielPerez\source\repos\ApiCreacionDocs\Img\APR_Firma_Hor_Fblanco_RGB.png"" width=""140"" height=""90"" />        ";
            strDocumento += @"    <br>                                                                                                                                                  ";
            strDocumento += @"    <br>                                                                                                                                                  ";
            strDocumento += @"    <p style=""margin:0;display:inline;float:left"">CRÉDITO EN CUENTA CORRIENTE</p>                                                                       ";
            strDocumento += @"    <p style=""margin:0;display:inline;float:right"">FECHA DE SOLICITUD	______________</p>                                                              ";
            strDocumento += @"    <br>                                                                                                                                                  ";
            strDocumento += @"    <br>                                                                                                                                                  ";
            strDocumento += @"    <br>                                                                                                                                                  ";
            strDocumento += @"    <table>                                                                                                                                               ";
            strDocumento += @"        <tr>                                                                                                                                              ";
            strDocumento += @"            <td></td>                                                                                                                                     ";
            strDocumento += @"            <td>                                                                                                                                          ";
            strDocumento += @"                <p class=""solid"" align=""center"" style=""width:550px;background-color:#E6E6E6;"">DATOS DEL SOLICITANTE</p>                             ";
            strDocumento += @"            </td>                                                                                                                                         ";
            strDocumento += @"            <td></td>                                                                                                                                     ";
            strDocumento += @"        </tr>                                                                                                                                             ";
            strDocumento += @"        <tr>                                                                                                                                              ";
            strDocumento += @"            <td>                                                                                                                                          ";
            strDocumento += @"                <p class=""b"">                                                                                                                           ";
            strDocumento += @"                    DEPENDENCIA<br>                                                                                                                       ";
            strDocumento += @"                    RETENEDORA DE<br>                                                                                                                     ";
            strDocumento += @"                    PAGOS:                                                                                                                                ";
            strDocumento += @"                </p>                                                                                                                                      ";
            strDocumento += @"            </td>                                                                                                                                         ";
            strDocumento += @"            <td>                                                                                                                                          ";
            strDocumento += @"                <p align=""center"" class=""b"">                                                                                                          ";
            strDocumento += @"                   "+ data.dataEstipulacion.retenedorP+"                                                                                                                             ";
            strDocumento += @"                </p>                                                                                                                                      ";
            strDocumento += @"                __________________________________________________________                                                                                ";
            strDocumento += @"            </td>                                                                                                                                         ";
            strDocumento += @"            <td><p class=""b"">ADSCRITO A:<p></td>                                                                                                        ";
            strDocumento += @"            <td>                                                                                                                                          ";
            strDocumento += @"                <p class=""solid"" align=""center"" style=""width:250px;"" class=""b"">" + data.dataEstipulacion.TrabajoArea + "</p>                                         ";
            strDocumento += @"            </td>                                                                                                                                         ";
            strDocumento += @"        </tr>                                                                                                                                             ";
            strDocumento += @"        <tr>                                                                                                                                              ";
            strDocumento += @"            <td>                                                                                                                                          ";
            strDocumento += @"                <br>                                                                                                                                      ";
            strDocumento += @"                <p class=""b"">NOMBRE:</p>                                                                                                                ";
            strDocumento += @"            </td>                                                                                                                                         ";
            strDocumento += @"            <td>                                                                                                                                          ";
            strDocumento += @"                <p align=""center"" class=""b"">                                                                                                          ";
            strDocumento += @"                   "+data.dataEstipulacion.NombreCliente+"                                                                                                                 ";
            strDocumento += @"                </p>                                                                                                                                      ";
            strDocumento += @"                ____________________________________________________________                                                                              ";
            strDocumento += @"            </td>                                                                                                                                         ";
            strDocumento += @"            <td>                                                                                                                                          ";
            strDocumento += @"                <p class=""b"">CLAVE DEL EMPLEADO:</p>                                                                                                    ";
            strDocumento += @"            </td>                                                                                                                                         ";
            strDocumento += @"            <td>                                                                                                                                          ";
            strDocumento += @"                <p class=""solid"" align=""center"" style=""width:150px;"" class=""b"">" + data.dataEstipulacion.ClaveEmpleado + "</p>                                                            ";
            strDocumento += @"            </td>                                                                                                                                         ";
            strDocumento += @"        </tr>                                                                                                                                             ";
            strDocumento += @"        <tr>                                                                                                                                              ";
            strDocumento += @"        <tr>                                                                                                                                              ";
            strDocumento += @"            <td>                                                                                                                                          ";
            strDocumento += @"                <br>                                                                                                                                      ";
            strDocumento += @"                <p class=""b"">DIRECCIÓN:</p>                                                                                                             ";
            strDocumento += @"            </td>                                                                                                                                         ";
            strDocumento += @"            <td>                                                                                                                                          ";
            strDocumento += @"                <p align=""center"" class=""b"">                                                                                                          ";
            strDocumento += @"                "+data.dataEstipulacion.DireccionCliente+"                                                                     ";
            strDocumento += @"                </p>                                                                                                                                      ";
            strDocumento += @"                ____________________________________________________________________                                                                      ";
            strDocumento += @"            </td>                                                                                                                                         ";
            strDocumento += @"            <td>                                                                                                                                          ";
            strDocumento += @"                <p class=""b""> CONTRATO NÚMERO: </p>                                                                                                     ";
            strDocumento += @"            </td>                                                                                                                                         ";
            strDocumento += @"            <td>                                                                                                                                          ";
            strDocumento += @"                <p class=""solid"" align=""center"" style=""width:150px;"" class=""b"">2220028840</p>                                                     ";
            strDocumento += @"            </td>                                                                                                                                         ";
            strDocumento += @"        </tr>                                                                                                                                             ";
            strDocumento += @"        <tr>                                                                                                                                              ";
            strDocumento += @"            <td>                                                                                                                                          ";
            strDocumento += @"                <br>                                                                                                                                      ";
            strDocumento += @"                <p class=""b"">TELEFONO:</p>                                                                                                              ";
            strDocumento += @"            </td>                                                                                                                                         ";
            strDocumento += @"            <td>                                                                                                                                          ";
            strDocumento += @"                <p align=""center"" class=""b"">                                                                                                          ";
            strDocumento += @"                    "+data.dataEstipulacion.TelefonoClientePart+ "&nbsp;&nbsp;&nbsp;/&nbsp;&nbsp;&nbsp;" + data.dataEstipulacion.TelefonoClienteOficina + "                                                                             ";
            strDocumento += @"                </p>                                                                                                                                      ";
            strDocumento += @"                ____________________________________________________________                                                                              ";
            strDocumento += @"                <P align=""center"" class=""b"">PARTICULAR &nbsp;&nbsp;&nbsp;/&nbsp;&nbsp;&nbsp;OFICINA</P>                                               ";
            strDocumento += @"            </td>                                                                                                                                         ";
            strDocumento += @"            <td>                                                                                                                                          ";
            strDocumento += @"                <p class=""b""> PLAZO DEL CRÉDITO:</p>                                                                                                    ";
            strDocumento += @"            </td>                                                                                                                                         ";
            strDocumento += @"            <td>                                                                                                                                          ";
            strDocumento += @"                <table>                                                                                                                                   ";
            strDocumento += @"                    <tr>                                                                                                                                  ";
            strDocumento += @"                        <td><p class=""b"">Meses</p></td>                                                                                                 ";
            strDocumento += @"                        <td><p class=""b"">Quincenas</p></td>                                                                                             ";
            strDocumento += @"                    </tr>                                                                                                                                 ";
            strDocumento += @"                    <tr>                                                                                                                                  ";
            strDocumento += @"                        <td><p class=""solid"" align=""center"" style=""width:50px;"" class=""b"">" + data.dataEstipulacion.PlazoCreditoMeses + "</p></td>                                             ";
            strDocumento += @"                        <td><p class=""solid"" align=""center"" style=""width:50px;"" class=""b"">" + data.dataEstipulacion.PlazoCreditoQNAS+ "</p></td>                                             ";
            strDocumento += @"                    </tr>                                                                                                                                 ";
            strDocumento += @"                </table>                                                                                                                                  ";
            strDocumento += @"            </td>                                                                                                                                         ";
            strDocumento += @"        </tr>                                                                                                                                             ";
            strDocumento += @"        <tr>                                                                                                                                              ";
            strDocumento += @"            <td>                                                                                                                                          ";
            strDocumento += @"                <br>                                                                                                                                      ";
            strDocumento += @"                <p class=""b"">                                                                                                                           ";
            strDocumento += @"                    PAGUESE A                                                                                                                             ";
            strDocumento += @"                    FAVOR DE:                                                                                                                             ";
            strDocumento += @"                </p>                                                                                                                                      ";
            strDocumento += @"            </td>                                                                                                                                         ";
            strDocumento += @"            <td>                                                                                                                                          ";
            strDocumento += @"                <p align=""center"" class=""b"">                                                                                                          ";
            strDocumento += @"                    FOMEPADE, S.A.P.I. DE CV, SOFOM E.N.R.                                                                                                ";
            strDocumento += @"                <p>                                                                                                                                       ";
            strDocumento += @"                    ____________________________________________________________                                                                          ";
            strDocumento += @"            </td>                                                                                                                                         ";
            strDocumento += @"            <td>                                                                                                                                          ";
            strDocumento += @"                <p class=""b"">                                                                                                                           ";
            strDocumento += @"                    MONTO DEL                                                                                                                             ";
            strDocumento += @"                    PRÉSTAMO:                                                                                                                             ";
            strDocumento += @"                <p>                                                                                                                                       ";
            strDocumento += @"            </td>                                                                                                                                         ";
            strDocumento += @"            <td>                                                                                                                                          ";
            strDocumento += @"                <p class=""b"">                                                                                                                           ";
            strDocumento += @"                  " + data.dataEstipulacion.MontoPrestamoSinInterSeguroLetra + "                                                                                            ";
            strDocumento += @"                <p>                                                                                                                                       ";
            strDocumento += @"                    __________________________________                                                                                                    ";
            strDocumento += @"                <p class=""b"" align=""center"">CON LETRA</p>                                                                                             ";
            strDocumento += @"            </td>                                                                                                                                         ";
            strDocumento += @"        </tr>                                                                                                                                             ";
            strDocumento += @"        <tr>                                                                                                                                              ";
            strDocumento += @"            <td>                                                                                                                                          ";
            strDocumento += @"                <br>                                                                                                                                      ";
            strDocumento += @"                <p class=""b"">                                                                                                                           ";
            strDocumento += @"                    MECANISMO DE                                                                                                                          ";
            strDocumento += @"                    PAGO:                                                                                                                                 ";
            strDocumento += @"                </p>                                                                                                                                      ";
            strDocumento += @"            </td>                                                                                                                                         ";
            strDocumento += @"            <td>                                                                                                                                          ";
            strDocumento += @"                <p align=""center"" class=""b"">                                                                                                          ";
            strDocumento += @"                    RANSFERENCIA INTERBANCARIA                                                                                                            ";
            strDocumento += @"                </p>                                                                                                                                      ";
            strDocumento += @"                ____________________________________________________________                                                                              ";
            strDocumento += @"            </td>                                                                                                                                         ";
            strDocumento += @"            <td></td>                                                                                                                                     ";
            strDocumento += @"        </tr>                                                                                                                                             ";
            strDocumento += @"        <tr>                                                                                                                                              ";
            strDocumento += @"            <td>                                                                                                                                          ";
            strDocumento += @"                <br>                                                                                                                                      ";
            strDocumento += @"                <p class=""b"">BANCO:</p>                                                                                                                 ";
            strDocumento += @"            </td>                                                                                                                                         ";
            strDocumento += @"            <td>                                                                                                                                          ";
            strDocumento += @"                <p align=""center"" class=""b"">                                                                                                          ";
            strDocumento += @"                    BBVA BANCOMER, S.A. DE C.V.                                                                                                           ";
            strDocumento += @"                </p>                                                                                                                                      ";
            strDocumento += @"                ____________________________________________________________                                                                              ";
            strDocumento += @"            </td>                                                                                                                                         ";
            strDocumento += @"            <td></td>                                                                                                                                     ";
            strDocumento += @"        </tr>                                                                                                                                             ";
            strDocumento += @"        <tr>                                                                                                                                              ";
            strDocumento += @"            <td>                                                                                                                                          ";
            strDocumento += @"                <br>                                                                                                                                      ";
            strDocumento += @"                <p class=""b"">SUCURSAL:</p>                                                                                                              ";
            strDocumento += @"            </td>                                                                                                                                         ";
            strDocumento += @"            <td>                                                                                                                                          ";
            strDocumento += @"                <p align=""center"" class=""b"">                                                                                                          ";
            strDocumento += @"                                " +"No Hay Sucursal"+ "                                                                                                                 ";
            strDocumento += @"                </p>                                                                                                                                      ";
            strDocumento += @"                ____________________________________________________________                                                                              ";
            strDocumento += @"            </td>                                                                                                                                         ";
            strDocumento += @"            <td></td>                                                                                                                                     ";
            strDocumento += @"        </tr>                                                                                                                                             ";
            strDocumento += @"        <tr>                                                                                                                                              ";
            strDocumento += @"            <td>                                                                                                                                          ";
            strDocumento += @"                <br>                                                                                                                                      ";
            strDocumento += @"                <p class=""b"">                                                                                                                           ";
            strDocumento += @"                    CUENTA DE                                                                                                                             ";
            strDocumento += @"                    DEPÓSITO:                                                                                                                             ";
            strDocumento += @"                </p>                                                                                                                                      ";
            strDocumento += @"            </td>                                                                                                                                         ";
            strDocumento += @"            <td>                                                                                                                                          ";
            strDocumento += @"                <p align=""center"" class=""b"">                                                                                                          ";
            strDocumento += @"                    " + data.dataEstipulacion.NoCuentaCTAClaveDeposito + "                                                                                        ";
            strDocumento += @"                </p>                                                                                                                                      ";
            strDocumento += @"                ____________________________________________________________<br>                                                                          ";
            strDocumento += @"                <p class=""b"" align=""center"">(CLABE BANCARIA)</p>                                                                                      ";
            strDocumento += @"                                                                                                                                                          ";
            strDocumento += @"            </td>                                                                                                                                         ";
            strDocumento += @"            <td></td>                                                                                                                                     ";
            strDocumento += @"        </tr>                                                                                                                                             ";
            strDocumento += @"    </table>                                                                                                                                              ";
            strDocumento += @"                                                                                                                                                          ";
            strDocumento += @"    <p class=""b"">                                                                                                                                       ";
            strDocumento += @"        EL ACREDITADO INSTRUYE EN ESTE ACTO A ""FOMEPADE, S.A.P.I. DE CV, SOFOM E.N.R."" PARA QUE LA DISPOSICIÓN DE EFECTIVO A QUE SE HACE REFERENCIA     ";
            strDocumento += @"        EN EL PRESENTE INSTRUMENTO SE REALICE MEDIANTE DEPÓSITO POR TRANSFERENCIA ELECTRÓNICA, POR LO QUE EL ACREDITADO EXPRESAMENTE ACEPTA               ";
            strDocumento += @"        COMO COMPROBANTE DE PAGO DE LA CANTIDAD DEL CRÉDITO, ESTABLECIDA EN ESTE MISMO INSTRUMENTO, AL AMPARO DEL CONTRATO DE LÍNEA DE CRÉDITO            ";
            strDocumento += @"        CELEBRADO CON ""FOMEPADE, S.A.P.I. DE CV, SOFOM E.N.R."", LOS DOCUMENTOS QUE EXPIDA LA INSTITUCIÓN DE CRÉDITO DESDE LA CUAL SE REALICE LA         ";
            strDocumento += @"        TRANSFERENCIA ELECTRÓNICA.                                                                                                                        ";
            strDocumento += @"    </p>                                                                                                                                                  ";
            strDocumento += @"    <p align=""right"" class=""b"">ZACATECAS, ZACATECAS A 10 DE FEBRERO DE 2020<p>                                                                        ";
            strDocumento += @"        <table>                                                                                                                                           ";
            strDocumento += @"            <tr>                                                                                                                                          ";
            strDocumento += @"                <td>                                                                                                                                      ";
            strDocumento += @"    <p class=""b"">                                                                                                                                       ";
            strDocumento += @"        PRESENTE:<br>                                                                                                                                     ";
            strDocumento += @"        SUSCRITO A:                                                                                                                                       ";
            strDocumento += @"    </p>                                                                                                                                                  ";
            strDocumento += @"    <p class=""b"">"+data.dataEstipulacion.NombreCliente+"</p>                                                                                                                  ";
            strDocumento += @"    ________________________________________________________                                                                                              ";
            strDocumento += @"    <table>                                                                                                                                               ";
            strDocumento += @"        <tr>                                                                                                                                              ";
            strDocumento += @"            <td><p class=""b"">NOMBRE(S)&nbsp;&nbsp;&nbsp;&nbsp;APELLIDO PATERNO&nbsp;&nbsp;&nbsp;&nbsp;APELLIDO MATERNO</p></td>                         ";
            strDocumento += @"        </tr>                                                                                                                                             ";
            strDocumento += @"                                                                                                                                                          ";
            strDocumento += @"    </table>                                                                                                                                              ";
            strDocumento += @"    <td>                                                                                                                                                  ";
            strDocumento += @"        <table>                                                                                                                                           ";
            strDocumento += @"            <tr>                                                                                                                                          ";
            strDocumento += @"                <td><p align=""center"" style=""width:50px;"" class=""b"">SEXO</p></td>                                                                   ";
            strDocumento += @"                <td><p align=""center"" style=""width:50px;"" class=""b"">M</p></td>                                                                      ";
            strDocumento += @"                <td><p class=""solid"" align=""center"" style=""width:30px;"" class=""b"""+data.dataEstipulacion.sexoMasculino+"</p></td>                                                      ";
            strDocumento += @"                <td><p align=""center"" style=""width:50px;"" class=""b"">F</p></td>                                                                      ";
            strDocumento += @"                <td><p class=""solid"" align=""center"" style=""width:30px;"" class=""b"">" + data.dataEstipulacion.sexoFemenino + "</p></td>                                                 ";
            strDocumento += @"            </tr>                                                                                                                                         ";
            strDocumento += @"        </table>                                                                                                                                          ";
            strDocumento += @"                                                                                                                                                          ";
            strDocumento += @"    </td>                                                                                                                                                 ";
            strDocumento += @"    </tr>                                                                                                                                                 ";
            strDocumento += @"    <tr>                                                                                                                                                  ";
            strDocumento += @"        <td>                                                                                                                                              ";
            strDocumento += @"            <p align=""center"" class=""b"">"+data.dataEstipulacion.ClaveEmpleado+"</p>                                                                                                       ";
            strDocumento += @"            _______________________________________                                                                                                       ";
            strDocumento += @"            <p align=""center"" class=""b"">NÚMERO DE EMPLEADO</p>                                                                                        ";
            strDocumento += @"        </td>                                                                                                                                             ";
            strDocumento += @"        <td>                                                                                                                                              ";
            strDocumento += @"            <p align=""center"" class=""b"">"+data.dataEstipulacion.CLIENTERFC+"</p>                                                                                             ";
            strDocumento += @"            _______________________________________                                                                                                       ";
            strDocumento += @"            <p align=""center"" class=""b"">RFC</p>                                                                                                       ";
            strDocumento += @"        </td>                                                                                                                                             ";
            strDocumento += @"                                                                                                                                                          ";
            strDocumento += @"    </tr>                                                                                                                                                 ";
            strDocumento += @"    <tr>                                                                                                                                                  ";
            strDocumento += @"        <td>                                                                                                                                              ";
            strDocumento += @"            <p align=""center"" class=""b"">" + data.dataEstipulacion.retenedorP + "</p>                                                                                                 ";
            strDocumento += @"            __________________________________                                                                                                            ";
            strDocumento += @"            <p align=""center"" class=""b"">DEPENDENCIA RETENEDORA DE PAGOS</p>                                                                           ";
            strDocumento += @"        </td>                                                                                                                                             ";
            strDocumento += @"        <td>                                                                                                                                              ";
            strDocumento += @"            <p align=""center"" class=""b"">" + data.dataEstipulacion.TrabajoArea + "</p>                                                                                         ";
            strDocumento += @"            __________________________________                                                                                                            ";
            strDocumento += @"            <p align=""center"" class=""b"">ÁREA</p>                                                                                                      ";
            strDocumento += @"        </td>                                                                                                                                             ";
            strDocumento += @"        <td>                                                                                                                                              ";
            strDocumento += @"            <p align=""center"" class=""b"">J" + data.dataEstipulacion.TrabajoPuesto + "/p>                                                                                        ";
            strDocumento += @"            __________________________________                                                                                                            ";
            strDocumento += @"            <p align=""center"" class=""b"">PUESTO</p>                                                                                                    ";
            strDocumento += @"        </td>                                                                                                                                             ";
            strDocumento += @"    <tr>                                                                                                                                                  ";
            strDocumento += @"        </table>                                                                                                                                          ";
            strDocumento += @"        <p class=""b"">                                                                                                                                   ";
            strDocumento += @"            ""HE CELEBRADO UN CONTRATO DE CRÉDITO CON ""FOMEPADE, S.A.P.I. DE CV, SOFOM E.N.R."" "" POR UN IMPORTE DE $ "+data.dataEstipulacion.Creditosininteresseguroletra+"     ";
            strDocumento += @"            , ASÍ COMO UNA COMISIÓN POR ADMINISTRACIÓN DEL CRÉDITO POR UN MONTO DE $ "+data.dataEstipulacion.Comisionotorgamiento+"       ";
            strDocumento += @"           Y HE ADQUIRIDO UN SEGURO POR UN IMPORTE DE $"+data.dataEstipulacion.SeguroTotalSin1Pago+" "+data.dataEstipulacion.SeguroTotalSin1PagoLetra+"       ";
            strDocumento += @"           LO CUAL SUMA UN IMPORTE DE $ "+data.dataEstipulacion.CredTotal+" "+data.dataEstipulacion.CredTotalLetra+" ";
            strDocumento += @"           CANTIDAD QUE DEBO CUBRIR EN "+data.dataEstipulacion.CredNumPagos+" PAGOS QUINCENALES POR LA CANTIDAD DE "+data.dataEstipulacion.CredMontoParcialidad+" "+data.dataEstipulacion.CredMontoParcialidad+"     ";
            strDocumento += @"            CADA UNO.                                                                                                                                     ";
            strDocumento += @"            EN MI CARÁCTER DE TRABAJADOR DE SECRETARIA DE GOBIERNO, CON EL OBJETO DE FACILITAR EL PAGO A PLAZOS DEL CONTRATO DE CRÉDITO, DE               ";
            strDocumento += @"            MANERA IRREVOCABLE ESTIPULO A FAVOR DE FOMEPADE, S.A.P.I. DE CV, SOFOM E.N.R. EL DESCUENTO DE MI NOMINA DE CANTIDADES IGUALES A LAS           ";
            strDocumento += @"            QUE EXIGE MI OBLIGACIÓN DE PAGOS QUINCENALES QUE SE INDICAN EN EL PÁRRAFO QUE ANTECEDE, MISMOS QUE DEBERÁN SER DESCONTADOS POR                ";
            strDocumento += @"            TESORERIA EN APEGO A ESTA ESTIPULACIÓN Y ENTREGADOS A FOMEPADE, S.A.P.I. DE CV, SOFOM E.N.R. EN LA CUENTA BANCARIA 0188202664 O MEDIANTE      ";
            strDocumento += @"            TRANSFERENCIA BANCARIA A LA CLABE 012180001882026643. EL DESCUENTO DEBERÁ LLEVARSE A CABO UTILIZANDO LA CLAVE ÚNICA DE DEDUCCIÓN              ";
            strDocumento += @"            IDENTIFICADA CON EL NÚMERO DE CÓDIGO APRECIA FINANCIERA Y LA DENOMINACIÓN FOMEPADE.                                                           ";
            strDocumento += @"        </p>                                                                                                                                              ";
            strDocumento += @"        <p class=""b"">                                                                                                                                   ";
            strDocumento += @"            LOS DESCUENTOS DEBERÁN SER REALIZADOS A PARTIR DE LA FECHA DE FIRMA DEL CONTRATO DE CRÉDITO QUE HE SUSCRITO, CON LA PERIODICIDAD              ";
            strDocumento += @"            QUINCENAL NECESARIA HASTA QUE QUEDE CUBIERTO EL CRÉDITO OTORGADO EN MI FAVOR.                                                                 ";
            strDocumento += @"        </p>                                                                                                                                              ";
            strDocumento += @"        <p class=""b"">                                                                                                                                   ";
            strDocumento += @"            LOS DESCUENTOS SE REALIZARAN DE LAS PERCEPCIONES QUE QUINCENALMENTE RECIBO. EN CASO DE QUE SE TERMINE LA RELACIÓN DE TRABAJO, ME              ";
            strDocumento += @"            OBLIGO AL PAGO TOTAL, RELEVANDO AL H. TESORERIA DE CUALQUIER RESPONSABILIDAD DE PAGO.                                                         ";
            strDocumento += @"        </p>                                                                                                                                              ";
            strDocumento += @"        <p class=""b"" align=""center"">ATENTAMENTE</p>                                                                                                   ";
            strDocumento += @"        <p class=""b"" align=""center"">" + data.dataEstipulacion.NombreCliente + "</p>                                                                                             ";
            strDocumento += @"        <p class=""b"" align=""center"">____________________________</p>                                                                                  ";
            strDocumento += @"        <p class=""b"" align=""center"">NOMBRE Y FIRMA DEL TRABAJADOR ACREDITADO</p>                                                                      ";
            strDocumento += @"</body>                                                                                                                                                   ";
            strDocumento += @"</html>                                                                                                                                                   "; 


            return strDocumento;
        }
    }
}
