using ApiCreacionDocs.Models;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OriginaWebApp.Models.Formatos
{
    public class fmtfmtReferenciaDePag
    {
        public string strDocumento;

        public string FormatoHTML(InputData data)
        {


            strDocumento = @"<!doctype html>																																												";
            strDocumento += @"<html>                                                                                                                                                                                       ";
            strDocumento += @"<head>                                                                                                                                                                                       ";
            strDocumento += @"    <style>                                                                                                                                                                                  ";
            strDocumento += @"        p.b {                                                                                                                                                                                ";
            strDocumento += @"            font-family: Arial;                                                                                                                                                              ";
            strDocumento += @"            font-size: 12px;                                                                                                                                                                 ";
            strDocumento += @"        }                                                                                                                                                                                    ";
            strDocumento += @"                                                                                                                                                                                             ";
            strDocumento += @"        u.b {                                                                                                                                                                                ";
            strDocumento += @"            font-family: Arial;                                                                                                                                                              ";
            strDocumento += @"            font-size: 12px;                                                                                                                                                                 ";
            strDocumento += @"        }                                                                                                                                                                                    ";
            strDocumento += @"        p.negrita {                                                                                                                                                                          ";
            strDocumento += @"            font-family: Arial;                                                                                                                                                              ";
            strDocumento += @"            font-weight: bold;                                                                                                                                                               ";
            strDocumento += @"        }                                                                                                                                                                                    ";
            strDocumento += @"        font.l {                                                                                                                                                                             ";
            strDocumento += @"            font-weight: bold;                                                                                                                                                               ";
            strDocumento += @"        }                                                                                                                                                                                    ";
            strDocumento += @"        font.z {                                                                                                                                                                             ";
            strDocumento += @"            text-align: right;                                                                                                                                                               ";
            strDocumento += @"        }                                                                                                                                                                                    ";
            strDocumento += @"    </style>                                                                                                                                                                                 ";
            strDocumento += @"</head>                                                                                                                                                                                      ";
            strDocumento += @"<body style=""text-align: justify;"">                                                                                                                                                        ";
            strDocumento += @"    <div>                                                                                                                                                                                    ";
            strDocumento += @"        <div style=""clear:both;"">                                                                                                                                                          ";
            strDocumento += @"            <table cellpadding=""0"" cellspacing=""0"" style=""width:100%; border-collapse:collapse;"">                                                                                      ";
            strDocumento += @"                <tbody>                                                                                                                                                                      ";
            strDocumento += @"                    <tr style=""height:36.75pt;"">                                                                                                                                           ";
            strDocumento += @"                        <td style=""width:73.5pt; vertical-align:top;"">                                                                                                                     ";
            strDocumento += @"                            <p style=""margin-top:0pt; margin-bottom:0pt; line-height:0%; font-size:1pt;"">                                                                                  ";
            strDocumento += @"							<span style=""font-family:Calibri;"">&nbsp;</span></p>                                                                                                              ";
            strDocumento += @"                        </td>                                                                                                                                                                ";
            strDocumento += @"                        <td style=""width:237.75pt; vertical-align:top;"">                                                                                                                   ";
            strDocumento += @"                            <p style=""margin-top:0pt; margin-bottom:0pt; line-height:0%; font-size:1pt;"">                                                                                  ";
            strDocumento += @"							<span style=""font-family:Calibri;"">&nbsp;</span></p>                                                                                                              ";
            strDocumento += @"                        </td>                                                                                                                                                                ";
            strDocumento += @"                        <td style=""width:68.25pt; vertical-align:top;"">                                                                                                                    ";
            strDocumento += @"                            <p style=""margin-top:0pt; margin-bottom:0pt; line-height:0%; font-size:1pt;"">                                                                                  ";
            strDocumento += @"							<span style=""font-family:Calibri;"">&nbsp;</span></p>                                                                                                              ";
            strDocumento += @"                        </td>                                                                                                                                                                ";
            strDocumento += @"                        <td rowspan=""2"" style=""width:113.25pt; vertical-align:top;"">                                                                                                     ";
            strDocumento += @"                            <p style=""margin-top:0pt; margin-bottom:0pt; font-size:1pt;"">                                                                                                  ";
            strDocumento += @"							<img src=""https://myfiles.space/user_files/74326_110ad65ee8cab72e/1610401219_referenciaunicadepago/1610401219_referenciaunicadepago.001.png""                      ";
            strDocumento += @"							width=""151"" height=""76"" alt=""ooxWord://media/image.png""></p>                                                                                                  ";
            strDocumento += @"                        </td>                                                                                                                                                                ";
            strDocumento += @"                        <td style=""width:45pt; vertical-align:top;"">                                                                                                                       ";
            strDocumento += @"                            <p style=""margin-top:0pt; margin-bottom:0pt; line-height:0%; font-size:1pt;"">                                                                                  ";
            strDocumento += @"							<span style=""font-family:Calibri;"">&nbsp;</span></p>                                                                                                              ";
            strDocumento += @"                        </td>                                                                                                                                                                ";
            strDocumento += @"                    </tr>                                                                                                                                                                    ";
            strDocumento += @"                    <tr style=""height:19.5pt;"">                                                                                                                                            ";
            strDocumento += @"                        <td style=""width:73.5pt; vertical-align:top;"">                                                                                                                     ";
            strDocumento += @"                            <p style=""margin-top:0pt; margin-bottom:0pt; line-height:0%; font-size:1pt;""><span style=""font-family:Calibri;"">&nbsp;</span></p>                            ";
            strDocumento += @"                        </td>                                                                                                                                                                ";
            strDocumento += @"                        <td style=""width:237.75pt; vertical-align:middle; background-color:#d3d3d3;"">                                                                                      ";
            strDocumento += @"                            <p style=""margin-top:0pt; margin-bottom:0pt; text-align:center; line-height:15pt;""><strong><span style=""font-family:Arial; font-size:13pt;"">                 ";
            strDocumento += @"							Referencia única de Pago</span></strong></p>                                                                                                                        ";
            strDocumento += @"                        </td>                                                                                                                                                                ";
            strDocumento += @"                        <td style=""width:68.25pt; vertical-align:top;"">                                                                                                                    ";
            strDocumento += @"                            <p style=""margin-top:0pt; margin-bottom:0pt; line-height:0%; font-size:1pt;""><span style=""font-family:Calibri;"">&nbsp;</span></p>                            ";
            strDocumento += @"                        </td>                                                                                                                                                                ";
            strDocumento += @"                        <td style=""width:45pt; vertical-align:top;"">                                                                                                                       ";
            strDocumento += @"                            <p style=""margin-top:0pt; margin-bottom:0pt; line-height:0%; font-size:1pt;""><span style=""font-family:Calibri;"">&nbsp;</span></p>                            ";
            strDocumento += @"                        </td>                                                                                                                                                                ";
            strDocumento += @"                    </tr>                                                                                                                                                                    ";
            strDocumento += @"                    <tr style=""height:3pt;"">                                                                                                                                               ";
            strDocumento += @"                        <td style=""width:73.5pt; vertical-align:top;"">                                                                                                                     ";
            strDocumento += @"                            <p style=""margin-top:0pt; margin-bottom:0pt; line-height:0%; font-size:1pt;""><span style=""font-family:Calibri;"">&nbsp;</span></p>                            ";
            strDocumento += @"                        </td>                                                                                                                                                                ";
            strDocumento += @"                        <td style=""width:237.75pt; vertical-align:top;"">                                                                                                                   ";
            strDocumento += @"                            <p style=""margin-top:0pt; margin-bottom:0pt; line-height:0%; font-size:1pt;""><span style=""font-family:Calibri;"">&nbsp;</span></p>                            ";
            strDocumento += @"                        </td>                                                                                                                                                                ";
            strDocumento += @"                        <td style=""width:68.25pt; vertical-align:top;"">                                                                                                                    ";
            strDocumento += @"                            <p style=""margin-top:0pt; margin-bottom:0pt; line-height:0%; font-size:1pt;""><span style=""font-family:Calibri;"">&nbsp;</span></p>                            ";
            strDocumento += @"                        </td>                                                                                                                                                                ";
            strDocumento += @"                        <td style=""width:113.25pt; vertical-align:top;"">                                                                                                                   ";
            strDocumento += @"                            <p style=""margin-top:0pt; margin-bottom:0pt; line-height:0%; font-size:1pt;""><span style=""font-family:Calibri;"">&nbsp;</span></p>                            ";
            strDocumento += @"                        </td>                                                                                                                                                                ";
            strDocumento += @"                        <td style=""width:45pt; vertical-align:top;"">                                                                                                                       ";
            strDocumento += @"                            <p style=""margin-top:0pt; margin-bottom:0pt; line-height:0%; font-size:1pt;""><span style=""font-family:Calibri;"">&nbsp;</span></p>                            ";
            strDocumento += @"                        </td>                                                                                                                                                                ";
            strDocumento += @"                    </tr>                                                                                                                                                                    ";
            strDocumento += @"                </tbody>                                                                                                                                                                     ";
            strDocumento += @"            </table>                                                                                                                                                                         ";
            strDocumento += @"            <p><b>En qué momento debe hacer uso de estos datos:</b></p>                                                                                                                      ";
            strDocumento += @"            <table>                                                                                                                                                                          ";
            strDocumento += @"                <tr>                                                                                                                                                                         ";
            strDocumento += @"                    <td>                                                                                                                                                                     ";
            strDocumento += @"                        <p>                                                                                                                                                                  ";
            strDocumento += @"                            <b>                                                                                                                                                              ";
            strDocumento += @"                                • Baja de la dependencia<br>                                                                                                                                 ";
            strDocumento += @"                                • Permiso sin goce de sueldo<br>                                                                                                                             ";
            strDocumento += @"                                • Renuncia voluntaria<br>                                                                                                                                    ";
            strDocumento += @"                                • Abono a capital<br>                                                                                                                                        ";
            strDocumento += @"                                • Liquidación antícipada<br>                                                                                                                                 ";
            strDocumento += @"                                • Pago por domiciliación no realizada                                                                                                                        ";
            strDocumento += @"                            </b>                                                                                                                                                             ";
            strDocumento += @"                        </p>                                                                                                                                                                 ";
            strDocumento += @"                    </td>                                                                                                                                                                    ";
            strDocumento += @"            </table>                                                                                                                                                                         ";
            strDocumento += @"            <p><b>DATOS DEL CRÉDITO</b></p>                                                                                                                                                  ";
            strDocumento += @"            <p>FECHA DE OPERACIÓN:<b>  29/02/2020</b></p>                                                                                                                                    ";
            strDocumento += @"            <p>PAGO: <b> QUINCENAL  $ 2,081.22</b></p>                                                                                                                                       ";
            strDocumento += @"            <p>                                                                                                                                                                              ";
            strDocumento += @"                NOMBRE:  JESUS RAMOS LOPEZ,  se obliga a pagar a “APRECIA” de acuerdo a la tabla de amorƟzaciones la cual formara                                                            ";
            strDocumento += @"                parte integral del contrato.                                                                                                                                                 ";
            strDocumento += @"            </p>                                                                                                                                                                             ";
            strDocumento += @"            <p>                                                                                                                                                                              ";
            strDocumento += @"                En caso de incumplimiento de contrato se procederá a   cobrar adicional a lo esƟpulado por la tabla de amorƟzaciones,                                                        ";
            strDocumento += @"                intereses moratorios y gastos de cobranza.                                                                                                                                   ";
            strDocumento += @"            </p>                                                                                                                                                                             ";
            strDocumento += @"            <p>                                                                                                                                                                              ";
            strDocumento += @"                A conƟnuación le proporcionamos las referencias con las que usted podrá realizar sus pagos QUINCENALES de su crédito                                                         ";
            strDocumento += @"                número:  C-2220028840. <br>                                                                                                                                                  ";
            strDocumento += @"                Es muy importante realizar el pago en la  fecha que le corresponda, y en el número de REFERENCIA correcta.                                                                   ";
            strDocumento += @"            </p>                                                                                                                                                                             ";
            strDocumento += @"            <p><b>FORMAS DE PAGO</b></p>                                                                                                                                                     ";
            strDocumento += @"            <p>1)  BBVA BANCOMER</p>                                                                                                                                                         ";
            strDocumento += @"            <p>                                                                                                                                                                              ";
            strDocumento += @"                Paga a través de (a) la PractiCaja con la opción ""Pago de Servicios"", (b) BancomerMovil en la opción ""Pagar""                                                             ";
            strDocumento += @"                elige ""Servicios"" y busca la opción ""Otro"", (c) en Ventanilla del banco:                                                                                                 ";
            strDocumento += @"            </p>                                                                                                                                                                             ";
            strDocumento += @"            <DIV align=""center"">                                                                                                                                                           ";
            strDocumento += @"                                                                                                                                                                                             ";
            strDocumento += @"                <table>                                                                                                                                                                      ";
            strDocumento += @"                    <tr>                                                                                                                                                                     ";
            strDocumento += @"                        <td>                                                                                                                                                                 ";
            strDocumento += @"                            <p class=""b"">CUENTA BANCARIA<br>___________________</p>                                                                                                        ";
            strDocumento += @"                        </td>                                                                                                                                                                ";
            strDocumento += @"                        <td><p class=""b"">REFERENCIA Y CONCEPTO DE PAGO<br>_____________________</p>                                                                                        ";
            strDocumento += @"                                                                                                                                                                                             ";
            strDocumento += @"                    </tr>                                                                                                                                                                    ";
            strDocumento += @"                    <tr>                                                                                                                                                                     ";
            strDocumento += @"                        <td><p>0188202664<br>___________________</p></td>                                                                                                                    ";
            strDocumento += @"                        <td><p>22200288409<br>___________________</p></td>                                                                                                                   ";
            strDocumento += @"                                                                                                                                                                                             ";
            strDocumento += @"                    </tr>                                                                                                                                                                    ";
            strDocumento += @"                </table>                                                                                                                                                                     ";
            strDocumento += @"            </DIV>                                                                                                                                                                           ";
            strDocumento += @"            <p>2)  OXXO Muestra el Código de Barras o la referencia numérica cuando vayas a pagar:</p>                                                                                       ";
            strDocumento += @"            <DIV align=""center"">                                                                                                                                                           ";
            strDocumento += @"                <table>                                                                                                                                                                      ";
            strDocumento += @"                    <tr>                                                                                                                                                                     ";
            strDocumento += @"                        <td>                                                                                                                                                                 ";
            strDocumento += @"                            <p class=""b""><u>REFERENCIA</u></p>                                                                                                                             ";
            strDocumento += @"                            <p class=""b"">1600002220028840132073</p>                                                                                                                        ";
            strDocumento += @"                        </td>                                                                                                                                                                ";
            strDocumento += @"                                                                                                                                                                                             ";
            strDocumento += @"                    </tr>                                                                                                                                                                    ";
            strDocumento += @"                </table>                                                                                                                                                                     ";
            strDocumento += @"            </DIV>                                                                                                                                                                           ";
            strDocumento += @"            <p>3)  Si transĮeres desde Otros Bancos, capturar la referencia en ""Concepto"" o ""Motivo de Pago"":</p>                                                                        ";
            strDocumento += @"            <DIV align=""center"">                                                                                                                                                           ";
            strDocumento += @"                <table>                                                                                                                                                                      ";
            strDocumento += @"                    <tr>                                                                                                                                                                     ";
            strDocumento += @"                        <td>                                                                                                                                                                 ";
            strDocumento += @"                            <p class=""b"">BANCO O INSTITUCIÓN<br>___________________</p>                                                                                                    ";
            strDocumento += @"                        </td>                                                                                                                                                                ";
            strDocumento += @"                        <td><p class=""b"">CLABE INTERBANCARIA<br>___________________</p></td>                                                                                               ";
            strDocumento += @"                        <td><p class=""b"">CONCEPTO O MOTIVO DE PAGO<br>___________________</p></td>                                                                                         ";
            strDocumento += @"                    </tr>                                                                                                                                                                    ";
            strDocumento += @"                    <tr>                                                                                                                                                                     ";
            strDocumento += @"                        <td><p>BBVA BANCOMER<br>___________________<p></td>                                                                                                                  ";
            strDocumento += @"                        <td><p>012180001882026643<br>___________________<p></td>                                                                                                             ";
            strDocumento += @"                        <td><p>22200288409<br>___________________<p></td>                                                                                                                    ";
            strDocumento += @"                    </tr>                                                                                                                                                                    ";
            strDocumento += @"                </table>                                                                                                                                                                     ";
            strDocumento += @"            </DIV>                                                                                                                                                                           ";
            strDocumento += @"            <br>                                                                                                                                                                             ";
            strDocumento += @"            <p>                                                                                                                                                                              ";
            strDocumento += @"                Quedo enterado de las referencias en donde puedo realizar los pagos de mi crédito contratado.<br>                                                                            ";
            strDocumento += @"                Si usted tiene alguna duda o aclaración se puede comunicar al  01 800 990 91 92, Opción 1 ó 2, o en la página  www.aprecia.com.mx                                            ";
            strDocumento += @"            </p>                                                                                                                                                                             ";
            strDocumento += @"                                                                                                                                                                                             ";
            strDocumento += @"        </div>                                                                                                                                                                               ";
            strDocumento += @"</body>                                                                                                                                                                                      ";
            strDocumento += @"</html>                                                                                                                                                                                      ";

            return strDocumento;
        }
    }
}
