using ApiCreacionDocs.Models;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OriginaWebApp.Models.Formatos
{
    public class fmtfmtArticulosLegales
    {
        public string strDocumento;

        public string FormatoHTML(InputData data)
        {

            strDocumento = @"<!doctype html>																													";
            strDocumento += @"<html>                                                                                                                            ";
            strDocumento += @"<head>                                                                                                                            ";
            strDocumento += @"    <style>                                                                                                                       ";
            strDocumento += @"        p.b {                                                                                                                     ";
            strDocumento += @"            font-family: Arial;                                                                                                   ";
            strDocumento += @"            font-size: 12px;                                                                                                      ";
            strDocumento += @"        }                                                                                                                         ";
            strDocumento += @"        u.b {                                                                                                                     ";
            strDocumento += @"            font-family: Arial;                                                                                                   ";
            strDocumento += @"            font-size: 12px;                                                                                                      ";
            strDocumento += @"        }                                                                                                                         ";
            strDocumento += @"        p.negrita {                                                                                                               ";
            strDocumento += @"            font-family: Arial;                                                                                                   ";
            strDocumento += @"            font-weight: bold;                                                                                                    ";
            strDocumento += @"        }                                                                                                                         ";
            strDocumento += @"        font.l {                                                                                                                  ";
            strDocumento += @"            font-weight: bold;                                                                                                    ";
            strDocumento += @"        }                                                                                                                         ";
            strDocumento += @"        font.z {                                                                                                                  ";
            strDocumento += @"            text-align: right;                                                                                                    ";
            strDocumento += @"        }                                                                                                                         ";
            strDocumento += @"        td {                                                                                                                      ";
            strDocumento += @"            line-height: 15px;                                                                                                    ";
            strDocumento += @"            padding: 0 15px;                                                                                                      ";
            strDocumento += @"            text-align: justify;                                                                                                  ";
            strDocumento += @"            vertical-align: top;                                                                                                  ";
            strDocumento += @"            width: 50%;                                                                                                           ";
            strDocumento += @"        }                                                                                                                         ";
            strDocumento += @"            td.first {                                                                                                            ";
            strDocumento += @"                border-right: 3px solid #FFFFF;                                                                                   ";
            strDocumento += @"            }                                                                                                                     ";
            strDocumento += @"    </style>                                                                                                                      ";
            strDocumento += @"</head>                                                                                                                           ";
            strDocumento += @"<body style=""text-align: justify;"">                                                                                             ";
            strDocumento += @"    <br>                                                                                                                          ";
            strDocumento += @"    <br>                                                                                                                          ";
            strDocumento += @"    <table>                                                                                                                       ";
            strDocumento += @"        <tr>                                                                                                                      ";
            strDocumento += @"            <td class=""first"">                                                                                                  ";
            strDocumento += @"                <p class=""b"">                                                                                                   ";
            strDocumento += @"                    <b>                                                                                                           ";
            strDocumento += @"                        <u class=""b"">LEY GENERAL DE ORGANIZACIONES Y ACTIVIDADES AUXILIARES DEL CRÉDITO</u>                     ";
            strDocumento += @"                    </b>                                                                                                          ";
            strDocumento += @"                </p>                                                                                                              ";
            strDocumento += @"                <p class=""b"">                                                                                                   ";
            strDocumento += @"                    <b><u>ARTÍCULO 56.-</u></b> La inspección y vigilancia de las organizaciones auxiliares del crédito,          ";
            strDocumento += @"					casas de cambio y sociedades financieras de objeto múltiple reguladas queda confiada a la Comisión              ";
            strDocumento += @"					Nacional Bancaria y de Valores, la que tendrá, en lo que no se oponga a esta Ley, respecto de dichas            ";
            strDocumento += @"					organizaciones auxiliares del crédito, casas de cambio y sociedades financieras de objeto múltiple              ";
            strDocumento += @"					reguladas, todas las facultades que en materia de inspección y vigilancia le confiere la Ley de                 ";
            strDocumento += @"					Instituciones de Crédito para instituciones de banca múltiple, quien la llevará a cabo sujetándose              ";
            strDocumento += @"					a lo previsto en su ley, en el Reglamento respectivo y en las demás disposiciones que resulten aplicables.      ";
            strDocumento += @"					En lo que respecta a las sociedades financieras de objeto múltiple no reguladas, los centros cambiarios y       ";
            strDocumento += @"					los transmisores de dinero, la inspección y vigilancia de estas sociedades, se llevará a cabo por la            ";
            strDocumento += @"					mencionada Comisión, exclusivamente para verificar el cumplimiento de los preceptos a que se refiere            ";
            strDocumento += @"					el artículo 95 Bis de esta Ley y las disposiciones de carácter general que de éste deriven.                     ";
            strDocumento += @"					Las organizaciones auxiliares del crédito y casas de cambio deberán rendir a la Secretaría de                   ";
            strDocumento += @"					Hacienda y Crédito Público y a la Comisión Nacional Bancaria y de Valores, en la forma y términos               ";
            strDocumento += @"					que al efecto establezcan, los informes, documentos y pruebas que sobre su organización, operaciones,           ";
            strDocumento += @"					contabilidad, inversiones o patrimonio les soliciten para fines de regulación, supervisión, control,            ";
            strDocumento += @"					inspección, vigilancia, estadística y demás funciones que, conforme a esta Ley u otras disposiciones            ";
            strDocumento += @"					legales y administrativas, les corresponda ejercer.                                                             ";
            strDocumento += @"                </p>                                                                                                              ";
            strDocumento += @"                <p class=""b"">                                                                                                   ";
            strDocumento += @"                    <b><u>ARTÍCULO 87-B.-</u></b> El otorgamiento de crédito, así como la celebración de arrendamiento            ";
            strDocumento += @"					financiero o factoraje financiero podrán realizarse en forma habitual y profesional por cualquier               ";
            strDocumento += @"					persona sin necesidad de requerir autorización del Gobierno Federal para ello.<br>                              ";
            strDocumento += @"                    Para todos los efectos legales, solamente se considerará como sociedad financiera de objeto                   ";
            strDocumento += @"					múltiple a la sociedad anónima que cuente con un registro vigente ante la Comisión Nacional                     ";
            strDocumento += @"					para la Protección y Defensa de los Usuarios de Servicios Financieros, para lo cual deberán                     ";
            strDocumento += @"					ajustarse a los requisitos siguientes:<br>                                                                      ";
            strDocumento += @"                    I.	Deberán contemplar expresamente como objeto social principal la realización habitual y                  ";
            strDocumento += @"					profesional de una o más de las actividades de otorgamiento de crédito, arrendamiento financiero                ";
            strDocumento += @"					o factoraje financiero;<br>                                                                                     ";
            strDocumento += @"                    II.	En forma complementaria a las actividades mencionadas, podrán considerar como parte de su               ";
            strDocumento += @"					objeto social principal, la administración de cualquier tipo de cartera crediticia, así como                    ";
            strDocumento += @"					otorgar en arrendamiento bienes muebles o inmuebles, siempre que así se encuentre contemplado                   ";
            strDocumento += @"					en sus estatutos, en cuyo caso se considerarán como ingresos provenientes de su objeto principal,               ";
            strDocumento += @"					los ingresos, documentos o cuentas por cobrar que deriven de dichas actividades en tanto éstos no               ";
            strDocumento += @"					excedan del treinta por ciento del total de los ingresos de la sociedad;<br>                                    ";
            strDocumento += @"                    III.	 Deberán agregar a su denominación social la expresión ""sociedad financiera de objeto múltiple""       ";
            strDocumento += @"					o su acrónimo ""SOFOM"", seguido de las palabras ""entidad regulada"" o su abreviatura ""E.R."" o “entidad      ";
            strDocumento += @"					no regulada” o su abreviatura “E.N.R”, según corresponda;<br>                                                   ";
            strDocumento += @"                    IV.	 Deberán contar con el dictamen técnico favorable vigente a que se refiere el artículo 87-P de          ";
            strDocumento += @"					la presente Ley, tratándose de sociedades financieras de objeto múltiple no reguladas, y V.                     ";
            strDocumento += @"					Los demás que establezca la Comisión Nacional para la Protección y Defensa de los Usuarios                      ";
            strDocumento += @"					de Servicios Financieros mediante disposiciones de carácter general.<br>                                        ";
            strDocumento += @"                    Las sociedades financieras de objeto múltiple se reputarán entidades financieras, que podrán                  ";
            strDocumento += @"					ser sociedades financieras de objeto múltiple reguladas o sociedades financieras de objeto                      ";
            strDocumento += @"					múltiple no reguladas.<br>                                                                                      ";
            strDocumento += @"                    Las sociedades financieras de objeto múltiple reguladas serán aquellas que mantengan vínculos                 ";
            strDocumento += @"					patrimoniales con instituciones de crédito, sociedades financieras populares con Niveles de                     ";
            strDocumento += @"					Operación I a IV, sociedades financieras comunitarias con Niveles de Operación I a IV o con                     ";
            strDocumento += @"					sociedades cooperativas de ahorro y préstamo con Niveles de Operación I a IV; aquellas que                      ";
            strDocumento += @"					emitan valores de deuda a su cargo, inscritos en el Registro Nacional de Valores conforme a                     ";
            strDocumento += @"					la Ley del Mercado de Valores en términos de lo previsto en el párrafo siguiente; y aquellas                    ";
            strDocumento += @"					que obtengan la aprobación de la Comisión Nacional Bancaria y de Valores en términos del                        ";
            strDocumento += @"					artículo 87-C Bis 1 de esta Ley, para ajustarse al                                                              ";
            strDocumento += @"                </p>                                                                                                              ";
            strDocumento += @"                <p class=""b"">                                                                                                   ";
            strDocumento += @"                    El estado de cuenta citado en el primer párrafo de este artículo deberá                                       ";
            strDocumento += @"                    contener los datos sobre la identificación del contrato o convenio en donde                                   ";
            strDocumento += @"                    conste el crédito, el factoraje financiero o el arrendamiento financiero que                                  ";
            strDocumento += @"                    se haya otorgado; el capital inicial dispuesto o, en su caso, el importe de las                               ";
            strDocumento += @"                    rentas determinadas; el capital o, en su caso, las rentas vencidas no                                         ";
            strDocumento += @"                    pagadas; el capital o, en su caso, las rentas pendientes por vencer; las                                      ";
            strDocumento += @"                    tasas de interés del crédito o, en su caso, la variabilidad de la renta                                       ";
            strDocumento += @"                    aplicable a las rentas determinables a cada período de pago; los intereses                                    ";
            strDocumento += @"                    moratorios generados; la tasa de interés aplicable a intereses moratorios, y                                  ";
            strDocumento += @"                    el importe de accesorios generados.                                                                           ";
            strDocumento += @"                                                                                                                                  ";
            strDocumento += @"                </p>                                                                                                              ";
            strDocumento += @"                <p align=""center"" class=""b""><b><u>LA LEY GENERAL DE TÍTULOS Y OPERACIONES DE CRÉDITO</u></b></p>              ";
            strDocumento += @"                <p class=""b"">                                                                                                   ";
            strDocumento += @"                    <b><u>ARTÍCULO 291.-</u></b> En virtud de la apertura de crédito, el acreditante se obliga                    ";
            strDocumento += @"                    a poner una suma de dinero a disposición del acreditado, o a contraer por                                     ";
            strDocumento += @"                    cuenta de éste una obligación, para que el mismo haga uso del crédito                                         ";
            strDocumento += @"                    concedido en la forma y en los términos y condiciones convenidos ,                                            ";
            strDocumento += @"                    quedando obligado el acreditado a restituir al acreditante las sumas de que                                   ";
            strDocumento += @"                    disponga, o a cubrirlo oportunamente por el importe de la obligación que                                      ";
            strDocumento += @"                    contrajo, y en todo caso a pagarle los intereses, prestaciones, gastos y                                      ";
            strDocumento += @"                    comisiones que se estipulen.                                                                                  ";
            strDocumento += @"                </p>                                                                                                              ";
            strDocumento += @"                <p class=""b"">                                                                                                   ";
            strDocumento += @"                    <b><u>ARTÍCULO 299.-</u></b> El otorgamiento o transmisión de un título de crédito o de                       ";
            strDocumento += @"                    cualquier otro documento por el acreditado al acreditante, como                                               ";
            strDocumento += @"                    reconocimiento del adeudo que a cargo de aquél resulte en virtud de las                                       ";
            strDocumento += @"                    disposiciones que haga del crédito concedido, no facultan al acreditante                                      ";
            strDocumento += @"                    para descontar o ceder el crédito así documentado, antes de su                                                ";
            strDocumento += @"                    vencimiento, sino hasta cuando el acreditado lo autorice a ello                                               ";
            strDocumento += @"                    expresamente.<br />                                                                                           ";
            strDocumento += @"                    Negociado o cedido el crédito por el acreditante, éste abonara al acreditado ,                                ";
            strDocumento += @"                    desde la fecha de tales actos, los intereses correspondientes al importe de                                   ";
            strDocumento += @"                    la disposición de que dicho crédito proceda, conforme al tipo estipulado en                                   ";
            strDocumento += @"                    la apertura de crédito; pero el crédito concedido no se entenderá renovado                                    ";
            strDocumento += @"                    por esa cantidad, sino cuando las partes así lo hayan convenido                                               ";
            strDocumento += @"                                                                                                                                  ";
            strDocumento += @"                </p>                                                                                                              ";
            strDocumento += @"                <p align=""center"" class=""b""><b><u>CODIGO DE PROCEDIMIENTOS CIVILES PARA EL DISTRITO FEDERAL</u></b></p>       ";
            strDocumento += @"                <p class=""b"">                                                                                                   ";
            strDocumento += @"                    <b><u>ARTÍCULO 443.-</u></b> para que el juicio ejecutivo tenga lugar se necesita un                          ";
            strDocumento += @"                    título que lleve aparejada ejecución.                                                                         ";
            strDocumento += @"                    Traen aparejada ejecución:                                                                                    ";
            strDocumento += @"                    I.- La primera copia de una escritura pública expedida por el juez o notario                                  ";
            strDocumento += @"                    ante quien se otorgó;<br />                                                                                   ";
            strDocumento += @"                    II.- Las ulteriores copias dadas por mandato judicial, con citación de la                                     ";
            strDocumento += @"                    persona a quien interesa;<br />                                                                               ";
            strDocumento += @"                    III.- Los demás instrumentos públicos que conforme al artículo 333 hacen                                      ";
            strDocumento += @"                    prueba plena;<br />                                                                                           ";
            strDocumento += @"                    IV.- Cualquier documento privado después de reconocido por quien lo hizo o                                    ";
            strDocumento += @"                    lo mando extender; basta con que se reconozca la firma aun cuando se                                          ";
            strDocumento += @"                    niegue la deuda;<br />                                                                                        ";
            strDocumento += @"                    V.- La confesión de la deuda hecha ante juez competente por el deudor o                                       ";
            strDocumento += @"                    por su representante con facultades para ello;<br />                                                          ";
            strDocumento += @"                    VI.- Los convenios celebrados en el curso de un juicio ante el juez, ya sea                                   ";
            strDocumento += @"                    de las partes entre sí o de terceros que se hubieren obligado como                                            ";
            strDocumento += @"                    fiadores, depositarios, o en cualquier otra forma;<br />                                                      ";
            strDocumento += @"                    VII.- Las pólizas originales de contratos celebrados con intervención de                                      ";
            strDocumento += @"                    corredor público;<br />                                                                                       ";
            strDocumento += @"                    VIII.- El juicio uniforme de contadores si las partes ante el juez o por                                      ";
            strDocumento += @"                    escritura pública o por escrito privado reconocido judicialmente se hubieren                                  ";
            strDocumento += @"                    sujetado a él expresamente o lo hubieren aprobado.                                                            ";
            strDocumento += @"                </p>                                                                                                              ";
            strDocumento += @"                <p class=""b"">                                                                                                   ";
            strDocumento += @"                    En los actos de comercio y en la formación de los mismos podrán emplearse                                     ";
            strDocumento += @"                    los medios electrónicos, ópticos o cualquier otra tecnología.                                                 ";
            strDocumento += @"                    Para efecto del presente Código, se deberán tomar en cuenta las siguientes                                    ";
            strDocumento += @"                    definiciones:<br />                                                                                           ";
            strDocumento += @"                    <b>Certificado:</b> Todo Mensaje de Datos u otro registro que confirme el vínculo                             ";
            strDocumento += @"                    entre un Firmante y los datos de creación de Firma Electrónica.<br />                                         ";
            strDocumento += @"                    <b>Datos de Creación de Firma Electrónica:</b> Son los datos únicos, como                                     ";
            strDocumento += @"                    códigos o claves criptográficas privadas, que el Firmante genera de manera                                    ";
            strDocumento += @"                    secreta y utiliza para crear su Firma Electrónica, a fin de lograr el vínculo                                 ";
            strDocumento += @"                    entre dicha Firma Electrónica y el Firmante.<br />                                                            ";
            strDocumento += @"                    <b>Destinatario:</b> La persona designada por el Emisor para recibir el Mensaje                               ";
            strDocumento += @"                    de Datos, pero que no esté actuando a título de Intermediario con respecto a                                  ";
            strDocumento += @"                    dicho Mensaje.                                                                                                ";
            strDocumento += @"                    <b>Digitalización:</b> Migración de documentos impresos a mensaje de datos, de                                ";
            strDocumento += @"                    acuerdo con lo dispuesto en la norma oficial mexicana sobre digitalización y                                  ";
            strDocumento += @"                    conservación de mensajes de datos que para tal efecto emita la Secretaría.<br />                              ";
            strDocumento += @"                    <b>Emisor:</b> Toda persona que, al tenor del Mensaje de Datos, haya actuado a                                ";
            strDocumento += @"                    nombre propio o en cuyo nombre se haya enviado o generado ese mensaje                                         ";
            strDocumento += @"                    antes de ser archivado, si éste es el caso, pero que no haya actuado a                                        ";
            strDocumento += @"                    título de Intermediario.<br />                                                                                ";
            strDocumento += @"                    <b>Firma Electrónica:</b> Los datos en forma electrónica consignados en un                                    ";
            strDocumento += @"                    Mensaje de Datos, o adjuntados o lógicamente asociados al mismo por                                           ";
            strDocumento += @"                    cualquier tecnología, que son utilizados para identificar al Firmante en                                      ";
            strDocumento += @"                    relación con el Mensaje de Datos e indicar que el Firmante aprueba la                                         ";
            strDocumento += @"                    información contenida en el Mensaje de Datos, y que produce los mismos                                        ";
            strDocumento += @"                    efectos jurídicos que la firma autógrafa, siendo admisible como prueba en                                     ";
            strDocumento += @"                    juicio. Firma Electrónica Avanzada o Fiable: Aquella Firma Electrónica que                                    ";
            strDocumento += @"                    cumpla con los requisitos contemplados en las fracciones I a IV del artículo                                  ";
            strDocumento += @"                    97. En aquellas disposiciones que se refieran a Firma Digital, se considerará                                 ";
            strDocumento += @"                    a ésta como una especie de la Firma Electrónica.<br />                                                        ";
            strDocumento += @"                    <b>Firmante:</b> La persona que posee los datos de la creación de la firma y que                              ";
            strDocumento += @"                    actúa en nombre propio o de la persona a la que representa.<br />                                             ";
            strDocumento += @"                    <b>Intermediario:</b> En relación con un determinado Mensaje de Datos, se                                     ";
            strDocumento += @"                    entenderá toda persona que, actuando por cuenta de otra, envíe, reciba o                                      ";
            strDocumento += @"                    archive dicho Mensaje o preste algún otro servicio con respecto a él.<br />                                   ";
            strDocumento += @"                    <b>Mensaje de Datos:</b> La información generada, enviada, recibida o                                         ";
            strDocumento += @"                    archivada por medios electrónicos, ópticos o cualquier otra tecnología.<br />                                 ";
            strDocumento += @"                    <b>Parte que Confía:</b> La persona que, siendo o no el Destinatario, actúa                                   ";
            strDocumento += @"                    sobre la base de un Certificado o de una Firma Electrónica.<br />                                             ";
            strDocumento += @"                    <b>Prestador de Servicios de Certificación:</b> La persona o institución                                      ";
            strDocumento += @"                    pública que preste servicios relacionados con firmas electrónicas, expide                                     ";
            strDocumento += @"                    los certificados o presta servicios relacionados como la conservación de                                      ";
            strDocumento += @"                    mensajes de datos, el sellado digital de tiempo y la digitalización de                                        ";
            strDocumento += @"                    documentos impresos, en los términos que se establezca en la norma oficial                                    ";
            strDocumento += @"                    mexicana sobre digitalización y conservación de mensajes de datos que                                         ";
            strDocumento += @"                    para tal efecto emita la Secretaría.<br />                                                                    ";
            strDocumento += @"                    <b>Secretaría:</b> Se entenderá la Secretaría de Economía.<br />                                              ";
            strDocumento += @"                    <b>Sello Digital de Tiempo:</b> El registro que prueba que un dato existía antes                              ";
            strDocumento += @"                    de la fecha y hora de emisión del citado Sello, en los términos que se                                        ";
            strDocumento += @"                    establezca en la norma oficial mexicana sobre digitalización y conservación                                   ";
            strDocumento += @"                    de mensajes de datos que para tal efecto emita la Secretaría.<br />                                           ";
            strDocumento += @"                    <b>Sistema de Información:</b> Se entenderá todo sistema utilizado para                                       ";
            strDocumento += @"                    generar, enviar, recibir, archivar o procesar de alguna otra forma Mensajes                                   ";
            strDocumento += @"                    de Datos.<br />                                                                                               ";
            strDocumento += @"                    <b>Titular del Certificado:</b> Se entenderá a la persona a cuyo favor fue                                    ";
            strDocumento += @"                    expedido el Certificado.                                                                                      ";
            strDocumento += @"                                                                                                                                  ";
            strDocumento += @"                </p>                                                                                                              ";
            strDocumento += @"            </td>                                                                                                                 ";
            strDocumento += @"            <td class=""second"">                                                                                                 ";
            strDocumento += @"                <p class=""b"">                                                                                                   ";
            strDocumento += @"                    aquellas que emitan valores de deuda a su cargo, inscritos en el Registro                                     ";
            strDocumento += @"                    Nacional de Valores conforme a la Ley del Mercado de Valores en términos                                      ";
            strDocumento += @"                    de lo previsto en el párrafo siguiente; y aquellas que obtengan la aprobación                                 ";
            strDocumento += @"                    de la Comisión Nacional Bancaria y de Valores en términos del artículo 87-C                                   ";
            strDocumento += @"                    Bis 1 de esta Ley, para ajustarse al régimen de entidad regulada, que no se                                   ";
            strDocumento += @"                    sitúen en alguno de los demás supuestos contemplados en este párrafo; y                                       ";
            strDocumento += @"                    estarán sujetas a la supervisión y vigilancia de la Comisión Nacional                                         ";
            strDocumento += @"                    Bancaria y de Valores de conformidad con lo dispuesto en el artículo 56 de                                    ";
            strDocumento += @"                    esta Ley, sin perjuicio de las atribuciones que esta Ley confiere a la                                        ";
            strDocumento += @"                    Comisión Nacional para la Protección y Defensa de los Usuarios de                                             ";
            strDocumento += @"                    Servicios Financieros en las normas aplicables.                                                               ";
            strDocumento += @"                    <br />                                                                                                        ";
            strDocumento += @"                    Para efectos de lo previsto en el párrafo anterior, se consideraran                                           ";
            strDocumento += @"                    sociedades financieras de objeto múltiple reguladas aquéllas que emitan                                       ";
            strDocumento += @"                    valores de deuda a su cargo, inscritos en el Registro Nacional de Valores                                     ";
            strDocumento += @"                    conforme a la Ley del Mercado de Valores, o bien, tratándose de títulos                                       ";
            strDocumento += @"                    fiduciarios igualmente inscritos en el citado Registro, cuando el cumplimiento                                ";
            strDocumento += @"                    de las obligaciones en relación con los títulos que se emitan al amparo del                                   ";
            strDocumento += @"                    fideicomiso dependan total o parcialmente de dicha sociedad, actuando                                         ";
            strDocumento += @"                    como fideicomitente, cedente o administrador del patrimonio fideicomitido, o                                  ";
            strDocumento += @"                    como garante o avalista de los referidos títulos.                                                             ";
            strDocumento += @"                    <br />                                                                                                        ";
            strDocumento += @"                    Las sociedades financieras de objeto múltiple no reguladas serán aquellas                                     ";
            strDocumento += @"                    que no se ubiquen en los supuestos de los párrafos anteriores.                                                ";
            strDocumento += @"                    Las sociedades financieras de objeto múltiple podrán actuar como                                              ";
            strDocumento += @"                    comisionistas de otras entidades financieras, en los términos y condiciones                                   ";
            strDocumento += @"                    que establezca la legislación y disposiciones aplicables a estas últimas.                                     ";
            strDocumento += @"                    Las sociedades financieras de objeto múltiple reguladas y no reguladas ,                                      ";
            strDocumento += @"                    deberán proporcionar la información o documentación que les requieran en                                      ";
            strDocumento += @"                    el ámbito de su competencia la Secretaría de Hacienda y Crédito Público, la                                   ";
            strDocumento += @"                    Comisión Nacional Bancaria y de Valores, el Banco de México y la Comisión                                     ";
            strDocumento += @"                    Nacional para la Protección y Defensa de los Usuarios de Servicios                                            ";
            strDocumento += @"                    Financieros, dentro de los plazos que tales autoridades señalen.                                              ";
            strDocumento += @"                    Las sociedades financieras de objeto múltiple no reguladas deberán                                            ";
            strDocumento += @"                    proporcionar a la Comisión Nacional para la Protección y Defensa de los                                       ";
            strDocumento += @"                    Usuarios de Servicios Financieros, la información agregada que ésta les                                       ";
            strDocumento += @"                    requiera con fines estadísticos.<br />                                                                        ";
            strDocumento += @"                    La Comisión Nacional Bancaria y de Valores, la Comisión Nacional para la                                      ";
            strDocumento += @"                    Protección y Defensa de los Usuarios de Servicios Financieros y el Banco                                      ";
            strDocumento += @"                    de México, en ejercicio de sus atribuciones de supervisión, inspección y                                      ";
            strDocumento += @"                    vigilancia, podrán imponer multas de doscientos a dos mil días de salario                                     ";
            strDocumento += @"                    mínimo general vigente en el Distrito Federal en la fecha de la infracción, a                                 ";
            strDocumento += @"                    las referidas sociedades, cuando éstas se abstengan de proporcionar la                                        ";
            strDocumento += @"                    información o documentación que cada autoridad les requiera, en los plazos                                    ";
            strDocumento += @"                    que se determinen, o bien, cuando la presenten de manera incorrecta o de                                      ";
            strDocumento += @"                    forma extemporánea.                                                                                           ";
            strDocumento += @"                    Las sociedades financieras de objeto múltiple no reguladas estarán sujetas                                    ";
            strDocumento += @"                    a la supervisión de la Comisión Nacional Bancaria y de Valores, de                                            ";
            strDocumento += @"                    conformidad con lo dispuesto por el segundo párrafo del artículo 56 de esta                                   ";
            strDocumento += @"                    Ley, para lo cual, la mencionada Comisión tomara como base la información                                     ";
            strDocumento += @"                    a que se refiere el artículo 87-K de la misma Ley.                                                            ";
            strDocumento += @"                </p>                                                                                                              ";
            strDocumento += @"                <p class=""b"">                                                                                                   ";
            strDocumento += @"                    <b><u>ARTÍCULO 87-F.-</u></b>                                                                                 ";
            strDocumento += @"                    El contrato en que se haga constar el crédito,                                                                ";
            strDocumento += @"                    arrendamiento financiero o factoraje financiero que otorguen las                                              ";
            strDocumento += @"                    sociedades financieras de objeto múltiple, siempre que dicho instrumento                                      ";
            strDocumento += @"                    vaya acompañado de la certificación del estado de cuenta respectivo a que                                     ";
            strDocumento += @"                    se refiere el artículo anterior, será título ejecutivo mercantil, sin necesidad                               ";
            strDocumento += @"                    de reconocimiento de firma ni de otro requisito alguno.                                                       ";
            strDocumento += @"                    Tratándose del factoraje financiero, además del contrato respectivo, las                                      ";
            strDocumento += @"                    sociedades financieras de objeto múltiple deberán contar con los                                              ";
            strDocumento += @"                    documentos que demuestren los derechos de crédito transmitidos por virtud                                     ";
            strDocumento += @"                    de dicha operación, así como la notificación al deudor de dicha transmisión                                   ";
            strDocumento += @"                    cuando ésta deba realizarse de acuerdo con las disposiciones aplicables.                                      ";
            strDocumento += @"                </p>                                                                                                              ";
            strDocumento += @"                <p class=""b"">                                                                                                   ";
            strDocumento += @"                    IX.- El estado de liquidación de adeudos, intereses moratorios y /o pena                                      ";
            strDocumento += @"                    convencional que se haya estipulado en la asamblea general de                                                 ";
            strDocumento += @"                    condóminos, suscrita por el administrador y/o comité vigilancia (sic), en el                                  ";
            strDocumento += @"                    que se incluya copia certificada por notario público o por la procuraduría                                    ";
            strDocumento += @"                    social del distrito federal, del acta de asamblea general relativa y /o del                                   ";
            strDocumento += @"                    reglamento interno del condominio o conjunto condominal, en el que se haya                                    ";
            strDocumento += @"                    determinado las cuotas a cargo de los condóminos o poseedores para los                                        ";
            strDocumento += @"                    fondos de mantenimiento, administración, reserva, intereses y demás                                           ";
            strDocumento += @"                    obligaciones de los condóminos. De acuerdo a lo estipulado en el párrafo                                      ";
            strDocumento += @"                    tercero del artículo 59 de la nueva ley de propiedad en condominio de                                         ";
            strDocumento += @"                    inmuebles para el distrito federal.<br />                                                                     ";
            strDocumento += @"                    X.- Los convenios emanados del procedimiento de mediación que cumplan                                         ";
            strDocumento += @"                    con los requisitos previstos en la ley de justicia alternativa del tribunal                                   ";
            strDocumento += @"                    superior de justicia para el distrito federal, y                                                              ";
            strDocumento += @"                    XI.- Los demás a los que se les reconozca ese carácter por la ley.                                            ";
            strDocumento += @"                </p>                                                                                                              ";
            strDocumento += @"                <p align=""center"" class=""b"">                                                                                  ";
            strDocumento += @"                    <b>                                                                                                           ";
            strDocumento += @"                        <u>                                                                                                       ";
            strDocumento += @"                            DISPOSICIONES DE CARÁCTER GENERAL EN MATERIA DE                                                       ";
            strDocumento += @"                            TRANSPARENCIA APLICABLES A LAS SOCIEDADES FINANCIERAS DE                                              ";
            strDocumento += @"                            OBJETO MÚLTIPLE, ENTIDADES NO REGULADAS.                                                              ";
            strDocumento += @"                        </u>                                                                                                      ";
            strDocumento += @"                    </b>                                                                                                          ";
            strDocumento += @"                </p>                                                                                                              ";
            strDocumento += @"                <p class=""b"">                                                                                                   ";
            strDocumento += @"                    <b><u>Artículo 6.-</u></b> Las Entidades Financieras deben entregar junto con el Contrato                     ";
            strDocumento += @"                    de Adhesión, una caratula por cada operación o servicio contratado. Dicha                                     ";
            strDocumento += @"                    caratula reunirá los siguientes requisitos:<br />                                                             ";
            strDocumento += @"                    I. Estar contenida en el máximo de una página, en tipografía de al menos 8                                    ";
            strDocumento += @"                    puntos;<br />                                                                                                 ";
            strDocumento += @"                    II. Ser personalizada a cada Usuario y contener la información actualizada al                                 ";
            strDocumento += @"                    momento de la contratación;<br />                                                                             ";
            strDocumento += @"                    III. Contener las características de la operación, respetando el formato y el                                 ";
            strDocumento += @"                    orden que se señala en el Anexo 1, sin agregar o eliminar información o                                       ";
            strDocumento += @"                    remitir a otro documento excepto cuando lo permita la guía de llenado                                         ";
            strDocumento += @"                    contenida en el propio Anexo, en tal forma que se permita al Usuario                                          ";
            strDocumento += @"                    comparar los servicios ofrecidos por diversas Entidades Financieras, y <br />                                 ";
            strDocumento += @"                    IV. En productos de crédito, cuando apliquen, incorporar las siguientes                                       ";
            strDocumento += @"                    leyendas de advertencia respecto a:<br />                                                                     ";
            strDocumento += @"                    a) Tasas de interés variable: “Al ser tu crédito de tasa variable, los                                        ";
            strDocumento += @"                    intereses pueden aumentar”;<br />                                                                             ";
            strDocumento += @"                    b) Comisiones que correspondan a penalidades para el Usuario y los                                            ";
            strDocumento += @"                    supuestos en que son aplicables: “Incumplir tus obligaciones te puede                                         ";
            strDocumento += @"                    generar Comisiones e intereses moratorios”;<br />                                                             ";
            strDocumento += @"                    c) Exceder la capacidad de pago: “Contratar créditos que excedan tu                                           ";
            strDocumento += @"                    capacidad de pago afecta tu historial crediticio”;<br />                                                      ";
            strDocumento += @"                    d) Pago mínimo en tarjeta de crédito: “Realizar solo el pago mínimo aumenta                                   ";
            strDocumento += @"                    el tiempo de pago y el costo de la deuda”;<br />                                                              ";
            strDocumento += @"                    e) Avalista, obligado solidario o coacreditado: “El avalista, obligado solidario                              ";
            strDocumento += @"                    o coacreditado responderá como obligado principal por el total del pago                                       ";
            strDocumento += @"                    frente a la Entidad Financiera”, o<br />                                                                      ";
            strDocumento += @"                    f) Crédito en moneda extranjera, UDI u otras variables: “Los montos a pagar                                   ";
            strDocumento += @"                    de este crédito varían conforme al comportamiento de la moneda o índice de                                    ";
            strDocumento += @"                    referencia.”.                                                                                                 ";
            strDocumento += @"                </p>                                                                                                              ";
            strDocumento += @"                <p align=""center"" class=""b"">                                                                                  ";
            strDocumento += @"                    <b>                                                                                                           ";
            strDocumento += @"                        <u>                                                                                                       ";
            strDocumento += @"                            CÓDIGO DE COMERCIO                                                                                    ";
            strDocumento += @"                        </u>                                                                                                      ";
            strDocumento += @"                    </b>                                                                                                          ";
            strDocumento += @"                </p>                                                                                                              ";
            strDocumento += @"                <p class=""b"">                                                                                                   ";
            strDocumento += @"                    <b><u>Artículo 89.-</u></b> Las disposiciones de este Título regirán en toda la República                     ";
            strDocumento += @"                    Mexicana en asuntos del orden comercial, sin perjuicio de lo dispuesto en                                     ";
            strDocumento += @"                    los tratados internacionales de los que México sea parte.<br />                                               ";
            strDocumento += @"                    Las actividades reguladas por este Título se someterán en su interpretación                                   ";
            strDocumento += @"                    y aplicación a los principios de neutralidad tecnológica, autonomía de la                                     ";
            strDocumento += @"                    voluntad, compatibilidad internacional y equivalencia funcional del Mensaje                                   ";
            strDocumento += @"                    de Datos en relación con la información documentada en medios no                                              ";
            strDocumento += @"                    electrónicos y de la Firma Electrónica en relación con la firma autógrafa.                                    ";
            strDocumento += @"                </p>                                                                                                              ";
            strDocumento += @"                <p class=""b"">                                                                                                   ";
            strDocumento += @"                    <b><u>Artículo 89 bis.-</u></b> No se negarán efectos jurídicos, validez o fuerza                             ";
            strDocumento += @"                    obligatoria a cualquier tipo de información por la sola razón de que esté                                     ";
            strDocumento += @"                    contenida en un Mensaje de Datos. Por tanto, dichos mensajes podrán ser                                       ";
            strDocumento += @"                    utilizados como medio probatorio en cualquier diligencia ante autoridad                                       ";
            strDocumento += @"                    legalmente reconocida, y surtirán los mismos efectos jurídicos que la                                         ";
            strDocumento += @"                    documentación impresa, siempre y cuando los mensajes de datos se                                              ";
            strDocumento += @"                    ajusten a las disposiciones de este Código y a los lineamientos normativos                                    ";
            strDocumento += @"                    correspondientes.                                                                                             ";
            strDocumento += @"                                                                                                                                  ";
            strDocumento += @"                </p>                                                                                                              ";
            strDocumento += @"            </td>                                                                                                                 ";
            strDocumento += @"        </tr>                                                                                                                     ";
            strDocumento += @"    </table>                                                                                                                      ";
            strDocumento += @"</body>                                                                                                                           ";
            strDocumento += @"</html>                                                                                                                           "; 

            return strDocumento;
        }
    }
}
